packages:
  - cms

ignoreDepScripts: true

ignoreWorkspaceRootCheck: true

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
  - workerd

onlyBuiltDependencies:
  - better-sqlite3
  - sharp
  - simple-git-hooks

overrides:
  '@unhead/vue': 2.1.1

savePrefix: ''

shellEmulator: true
