ignoreWorkspaceRootCheck: true

savePrefix: ''

shellEmulator: true

minimumReleaseAgeExclude:
  - '@nuxt/cli-nightly'
  - '@nuxt/cli'
  - '@comark/nuxt@0.6.1'
  - '@comark/vue@0.6.1'
  - comark@0.6.1

overrides:
  '@nuxt/cli': 'npm:@nuxt/cli-nightly@4.0.0-20260809-091242-57da795'
  rolldown: 1.2.3

allowBuilds:
  '*': false
  '@parcel/watcher': false
  core-js: false
  esbuild: false
  sharp: true
  simple-git-hooks: true
  unrs-resolver: false
  workerd: false
