ignoreWorkspaceRootCheck: true

overrides:
  vite: 8.0.16

savePrefix: ''

shellEmulator: true

allowBuilds:
  '*': false
  '@parcel/watcher': false
  better-sqlite3: true
  core-js: false
  esbuild: false
  sharp: true
  simple-git-hooks: true
  unrs-resolver: false
  workerd: false
