/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'community.lexicon.app.defs'

type $nsid = typeof $nsid

export { $nsid }

/** A labeled URI associated with an app. */
type Link = {
  $type?: 'community.lexicon.app.defs#link'

  /**
   * Destination URI.
   */
  uri: l.UriString

  /**
   * Human-readable label for the URI.
   */
  label?: string

  /**
   * Known role of this link, if any.
   */
  role?: LinkRole
}

export type { Link }

/** A labeled URI associated with an app. */
const link = /*#__PURE__*/ l.typedObject<Link>(
  $nsid,
  'link',
  /*#__PURE__*/ l.object({
    uri: /*#__PURE__*/ l.string({ format: 'uri' }),
    label: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 100, maxGraphemes: 50 }),
    ),
    role: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<LinkRole>((() => linkRole) as any),
    ),
  }),
)

export { link }

/** Known role of a link associated with an app. */
type LinkRole =
  | 'community.lexicon.app.defs#linkRoleWebsite'
  | 'community.lexicon.app.defs#linkRoleWebManifest'
  | 'community.lexicon.app.defs#linkRolePrivacyPolicy'
  | 'community.lexicon.app.defs#linkRoleTermsOfService'
  | 'community.lexicon.app.defs#linkRoleSupport'
  | 'community.lexicon.app.defs#linkRoleSourceCode'
  | 'community.lexicon.app.defs#linkRoleDocs'
  | 'community.lexicon.app.defs#linkRoleChangelog'
  | 'community.lexicon.app.defs#linkRoleStatus'
  | 'community.lexicon.app.defs#linkRoleAppStore'
  | 'community.lexicon.app.defs#linkRolePlayStore'
  | 'community.lexicon.app.defs#linkRoleFDroid'
  | l.UnknownString

export type { LinkRole }

/** Known role of a link associated with an app. */
const linkRole = /*#__PURE__*/ l.string<{
  knownValues: [
    'community.lexicon.app.defs#linkRoleWebsite',
    'community.lexicon.app.defs#linkRoleWebManifest',
    'community.lexicon.app.defs#linkRolePrivacyPolicy',
    'community.lexicon.app.defs#linkRoleTermsOfService',
    'community.lexicon.app.defs#linkRoleSupport',
    'community.lexicon.app.defs#linkRoleSourceCode',
    'community.lexicon.app.defs#linkRoleDocs',
    'community.lexicon.app.defs#linkRoleChangelog',
    'community.lexicon.app.defs#linkRoleStatus',
    'community.lexicon.app.defs#linkRoleAppStore',
    'community.lexicon.app.defs#linkRolePlayStore',
    'community.lexicon.app.defs#linkRoleFDroid',
  ]
}>()

export { linkRole }

/** Primary website or landing page. */
type LinkRoleWebsite = 'community.lexicon.app.defs#linkRoleWebsite'

export type { LinkRoleWebsite }

/** Primary website or landing page. */
const linkRoleWebsite = /*#__PURE__*/ l.token($nsid, 'linkRoleWebsite')

export { linkRoleWebsite }

/** Web App Manifest. */
type LinkRoleWebManifest = 'community.lexicon.app.defs#linkRoleWebManifest'

export type { LinkRoleWebManifest }

/** Web App Manifest. */
const linkRoleWebManifest = /*#__PURE__*/ l.token($nsid, 'linkRoleWebManifest')

export { linkRoleWebManifest }

/** Privacy policy. */
type LinkRolePrivacyPolicy = 'community.lexicon.app.defs#linkRolePrivacyPolicy'

export type { LinkRolePrivacyPolicy }

/** Privacy policy. */
const linkRolePrivacyPolicy = /*#__PURE__*/ l.token(
  $nsid,
  'linkRolePrivacyPolicy',
)

export { linkRolePrivacyPolicy }

/** Terms of service. */
type LinkRoleTermsOfService =
  'community.lexicon.app.defs#linkRoleTermsOfService'

export type { LinkRoleTermsOfService }

/** Terms of service. */
const linkRoleTermsOfService = /*#__PURE__*/ l.token(
  $nsid,
  'linkRoleTermsOfService',
)

export { linkRoleTermsOfService }

/** Support, help, or contact page. */
type LinkRoleSupport = 'community.lexicon.app.defs#linkRoleSupport'

export type { LinkRoleSupport }

/** Support, help, or contact page. */
const linkRoleSupport = /*#__PURE__*/ l.token($nsid, 'linkRoleSupport')

export { linkRoleSupport }

/** Source code repository or source distribution. */
type LinkRoleSourceCode = 'community.lexicon.app.defs#linkRoleSourceCode'

export type { LinkRoleSourceCode }

/** Source code repository or source distribution. */
const linkRoleSourceCode = /*#__PURE__*/ l.token($nsid, 'linkRoleSourceCode')

export { linkRoleSourceCode }

/** Documentation. */
type LinkRoleDocs = 'community.lexicon.app.defs#linkRoleDocs'

export type { LinkRoleDocs }

/** Documentation. */
const linkRoleDocs = /*#__PURE__*/ l.token($nsid, 'linkRoleDocs')

export { linkRoleDocs }

/** Changelog or release notes. */
type LinkRoleChangelog = 'community.lexicon.app.defs#linkRoleChangelog'

export type { LinkRoleChangelog }

/** Changelog or release notes. */
const linkRoleChangelog = /*#__PURE__*/ l.token($nsid, 'linkRoleChangelog')

export { linkRoleChangelog }

/** Service status page. */
type LinkRoleStatus = 'community.lexicon.app.defs#linkRoleStatus'

export type { LinkRoleStatus }

/** Service status page. */
const linkRoleStatus = /*#__PURE__*/ l.token($nsid, 'linkRoleStatus')

export { linkRoleStatus }

/** Apple App Store listing. */
type LinkRoleAppStore = 'community.lexicon.app.defs#linkRoleAppStore'

export type { LinkRoleAppStore }

/** Apple App Store listing. */
const linkRoleAppStore = /*#__PURE__*/ l.token($nsid, 'linkRoleAppStore')

export { linkRoleAppStore }

/** Google Play Store listing. */
type LinkRolePlayStore = 'community.lexicon.app.defs#linkRolePlayStore'

export type { LinkRolePlayStore }

/** Google Play Store listing. */
const linkRolePlayStore = /*#__PURE__*/ l.token($nsid, 'linkRolePlayStore')

export { linkRolePlayStore }

/** F-Droid listing. */
type LinkRoleFDroid = 'community.lexicon.app.defs#linkRoleFDroid'

export type { LinkRoleFDroid }

/** F-Droid listing. */
const linkRoleFDroid = /*#__PURE__*/ l.token($nsid, 'linkRoleFDroid')

export { linkRoleFDroid }

/** An image associated with an app, including accessibility and display metadata. Exactly one of `image` (ATProto blob) or `uri` (remote URL) MUST be present. Consumers SHOULD ignore image items that have neither or both. */
type Image = {
  $type?: 'community.lexicon.app.defs#image'

  /**
   * How directories and stores should use the image. Omit this field when no known purpose fits.
   */
  purpose?:
    | 'community.lexicon.app.defs#purposeIcon'
    | 'community.lexicon.app.defs#purposeLogo'
    | 'community.lexicon.app.defs#purposeHero'
    | 'community.lexicon.app.defs#purposeScreenshot'
    | 'community.lexicon.app.defs#purposeBanner'
    | 'community.lexicon.app.defs#purposeSocialCard'
    | 'community.lexicon.app.defs#purposeAppStore'
    | 'community.lexicon.app.defs#purposeAd'
    | l.UnknownString

  /**
   * The raw image file.
   */
  image?: l.BlobRef

  /**
   * Remote image URI.
   */
  uri?: l.UriString

  /**
   * Alt text description of the image, for accessibility.
   */
  alt: string
  aspectRatio?: AspectRatio
}

export type { Image }

/** An image associated with an app, including accessibility and display metadata. Exactly one of `image` (ATProto blob) or `uri` (remote URL) MUST be present. Consumers SHOULD ignore image items that have neither or both. */
const image = /*#__PURE__*/ l.typedObject<Image>(
  $nsid,
  'image',
  /*#__PURE__*/ l.object({
    purpose: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string<{
        knownValues: [
          'community.lexicon.app.defs#purposeIcon',
          'community.lexicon.app.defs#purposeLogo',
          'community.lexicon.app.defs#purposeHero',
          'community.lexicon.app.defs#purposeScreenshot',
          'community.lexicon.app.defs#purposeBanner',
          'community.lexicon.app.defs#purposeSocialCard',
          'community.lexicon.app.defs#purposeAppStore',
          'community.lexicon.app.defs#purposeAd',
        ]
      }>(),
    ),
    image: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.blob({ accept: ['image/*'], maxSize: 2000000 }),
    ),
    uri: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'uri' })),
    alt: /*#__PURE__*/ l.string({ maxLength: 1000, maxGraphemes: 300 }),
    aspectRatio: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<AspectRatio>((() => aspectRatio) as any),
    ),
  }),
)

export { image }

/** width:height represents an aspect ratio. It may be approximate. */
type AspectRatio = {
  $type?: 'community.lexicon.app.defs#aspectRatio'
  width: number
  height: number
}

export type { AspectRatio }

/** width:height represents an aspect ratio. It may be approximate. */
const aspectRatio = /*#__PURE__*/ l.typedObject<AspectRatio>(
  $nsid,
  'aspectRatio',
  /*#__PURE__*/ l.object({
    width: /*#__PURE__*/ l.integer({ minimum: 1 }),
    height: /*#__PURE__*/ l.integer({ minimum: 1 }),
  }),
)

export { aspectRatio }

/** A small square icon representing the app, typically used in launchers, lists, and tab bars. */
type PurposeIcon = 'community.lexicon.app.defs#purposeIcon'

export type { PurposeIcon }

/** A small square icon representing the app, typically used in launchers, lists, and tab bars. */
const purposeIcon = /*#__PURE__*/ l.token($nsid, 'purposeIcon')

export { purposeIcon }

/** A logotype or wordmark for the app. */
type PurposeLogo = 'community.lexicon.app.defs#purposeLogo'

export type { PurposeLogo }

/** A logotype or wordmark for the app. */
const purposeLogo = /*#__PURE__*/ l.token($nsid, 'purposeLogo')

export { purposeLogo }

/** A large promotional or feature image, typically used at the top of a directory listing. */
type PurposeHero = 'community.lexicon.app.defs#purposeHero'

export type { PurposeHero }

/** A large promotional or feature image, typically used at the top of a directory listing. */
const purposeHero = /*#__PURE__*/ l.token($nsid, 'purposeHero')

export { purposeHero }

/** A screenshot of the app's UI, used in directory and store listings. */
type PurposeScreenshot = 'community.lexicon.app.defs#purposeScreenshot'

export type { PurposeScreenshot }

/** A screenshot of the app's UI, used in directory and store listings. */
const purposeScreenshot = /*#__PURE__*/ l.token($nsid, 'purposeScreenshot')

export { purposeScreenshot }

/** A wide banner image, such as a header image for a profile or listing page. */
type PurposeBanner = 'community.lexicon.app.defs#purposeBanner'

export type { PurposeBanner }

/** A wide banner image, such as a header image for a profile or listing page. */
const purposeBanner = /*#__PURE__*/ l.token($nsid, 'purposeBanner')

export { purposeBanner }

/** An image sized and formatted for social media sharing previews (Open Graph, Twitter Card, etc.). */
type PurposeSocialCard = 'community.lexicon.app.defs#purposeSocialCard'

export type { PurposeSocialCard }

/** An image sized and formatted for social media sharing previews (Open Graph, Twitter Card, etc.). */
const purposeSocialCard = /*#__PURE__*/ l.token($nsid, 'purposeSocialCard')

export { purposeSocialCard }

/** A promotional image formatted for a native app store listing. */
type PurposeAppStore = 'community.lexicon.app.defs#purposeAppStore'

export type { PurposeAppStore }

/** A promotional image formatted for a native app store listing. */
const purposeAppStore = /*#__PURE__*/ l.token($nsid, 'purposeAppStore')

export { purposeAppStore }

/** A promotional or advertising image. */
type PurposeAd = 'community.lexicon.app.defs#purposeAd'

export type { PurposeAd }

/** A promotional or advertising image. */
const purposeAd = /*#__PURE__*/ l.token($nsid, 'purposeAd')

export { purposeAd }

/** Current release or maintenance status of an app. */
type Status =
  | 'community.lexicon.app.defs#unreleased'
  | 'community.lexicon.app.defs#preview'
  | 'community.lexicon.app.defs#released'
  | 'community.lexicon.app.defs#unmaintained'
  | 'community.lexicon.app.defs#discontinued'
  | l.UnknownString

export type { Status }

/** Current release or maintenance status of an app. */
const status = /*#__PURE__*/ l.string<{
  knownValues: [
    'community.lexicon.app.defs#unreleased',
    'community.lexicon.app.defs#preview',
    'community.lexicon.app.defs#released',
    'community.lexicon.app.defs#unmaintained',
    'community.lexicon.app.defs#discontinued',
  ]
}>()

export { status }

/** The app has been announced but is not yet available. */
type Unreleased = 'community.lexicon.app.defs#unreleased'

export type { Unreleased }

/** The app has been announced but is not yet available. */
const unreleased = /*#__PURE__*/ l.token($nsid, 'unreleased')

export { unreleased }

/** The app is available as an alpha, beta, early access, or preview release. */
type Preview = 'community.lexicon.app.defs#preview'

export type { Preview }

/** The app is available as an alpha, beta, early access, or preview release. */
const preview = /*#__PURE__*/ l.token($nsid, 'preview')

export { preview }

/** The app is generally available. */
type Released = 'community.lexicon.app.defs#released'

export type { Released }

/** The app is generally available. */
const released = /*#__PURE__*/ l.token($nsid, 'released')

export { released }

/** The app may still be available, but is no longer actively maintained. */
type Unmaintained = 'community.lexicon.app.defs#unmaintained'

export type { Unmaintained }

/** The app may still be available, but is no longer actively maintained. */
const unmaintained = /*#__PURE__*/ l.token($nsid, 'unmaintained')

export { unmaintained }

/** The app is no longer available or supported. */
type Discontinued = 'community.lexicon.app.defs#discontinued'

export type { Discontinued }

/** The app is no longer available or supported. */
const discontinued = /*#__PURE__*/ l.token($nsid, 'discontinued')

export { discontinued }

/** Platform where an app is available. */
type Platform =
  | 'community.lexicon.app.defs#platformWeb'
  | 'community.lexicon.app.defs#platformIOS'
  | 'community.lexicon.app.defs#platformAndroid'
  | 'community.lexicon.app.defs#platformMacOS'
  | 'community.lexicon.app.defs#platformWindows'
  | 'community.lexicon.app.defs#platformLinux'
  | 'community.lexicon.app.defs#platformCLI'
  | l.UnknownString

export type { Platform }

/** Platform where an app is available. */
const platform = /*#__PURE__*/ l.string<{
  knownValues: [
    'community.lexicon.app.defs#platformWeb',
    'community.lexicon.app.defs#platformIOS',
    'community.lexicon.app.defs#platformAndroid',
    'community.lexicon.app.defs#platformMacOS',
    'community.lexicon.app.defs#platformWindows',
    'community.lexicon.app.defs#platformLinux',
    'community.lexicon.app.defs#platformCLI',
  ]
}>()

export { platform }

/** Web app or website. */
type PlatformWeb = 'community.lexicon.app.defs#platformWeb'

export type { PlatformWeb }

/** Web app or website. */
const platformWeb = /*#__PURE__*/ l.token($nsid, 'platformWeb')

export { platformWeb }

/** iOS app. */
type PlatformIOS = 'community.lexicon.app.defs#platformIOS'

export type { PlatformIOS as PlatformIos }

/** iOS app. */
const platformIOS = /*#__PURE__*/ l.token($nsid, 'platformIOS')

export { platformIOS }

/** Android app. */
type PlatformAndroid = 'community.lexicon.app.defs#platformAndroid'

export type { PlatformAndroid }

/** Android app. */
const platformAndroid = /*#__PURE__*/ l.token($nsid, 'platformAndroid')

export { platformAndroid }

/** macOS app. */
type PlatformMacOS = 'community.lexicon.app.defs#platformMacOS'

export type { PlatformMacOS as PlatformMacOs }

/** macOS app. */
const platformMacOS = /*#__PURE__*/ l.token($nsid, 'platformMacOS')

export { platformMacOS }

/** Windows app. */
type PlatformWindows = 'community.lexicon.app.defs#platformWindows'

export type { PlatformWindows }

/** Windows app. */
const platformWindows = /*#__PURE__*/ l.token($nsid, 'platformWindows')

export { platformWindows }

/** Linux app. */
type PlatformLinux = 'community.lexicon.app.defs#platformLinux'

export type { PlatformLinux }

/** Linux app. */
const platformLinux = /*#__PURE__*/ l.token($nsid, 'platformLinux')

export { platformLinux }

/** Command line interface. */
type PlatformCLI = 'community.lexicon.app.defs#platformCLI'

export type { PlatformCLI as PlatformCli }

/** Command line interface. */
const platformCLI = /*#__PURE__*/ l.token($nsid, 'platformCLI')

export { platformCLI }

/** Self-declared AT Protocol lexicon interoperability signals. */
type LexiconInterop = {
  $type?: 'community.lexicon.app.defs#lexiconInterop'

  /**
   * Lexicon collections this app creates or publishes records for.
   */
  produces?: l.NsidString[]

  /**
   * Lexicon collections this app reads, displays, imports, or otherwise consumes.
   */
  consumes?: l.NsidString[]
}

export type { LexiconInterop }

/** Self-declared AT Protocol lexicon interoperability signals. */
const lexiconInterop = /*#__PURE__*/ l.typedObject<LexiconInterop>(
  $nsid,
  'lexiconInterop',
  /*#__PURE__*/ l.object({
    produces: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ format: 'nsid' })),
    ),
    consumes: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ format: 'nsid' })),
    ),
  }),
)

export { lexiconInterop }

/** A record whose presence in an account can indicate that the account probably uses this app. */
type AccountIndicator = {
  $type?: 'community.lexicon.app.defs#accountIndicator'

  /**
   * Record collection to look for in an account repository.
   */
  collection: l.NsidString

  /**
   * Optional record key to look for within the collection.
   */
  rkey?: l.RecordKeyString
}

export type { AccountIndicator }

/** A record whose presence in an account can indicate that the account probably uses this app. */
const accountIndicator = /*#__PURE__*/ l.typedObject<AccountIndicator>(
  $nsid,
  'accountIndicator',
  /*#__PURE__*/ l.object({
    collection: /*#__PURE__*/ l.string({ format: 'nsid' }),
    rkey: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'record-key' }),
    ),
  }),
)

export { accountIndicator }
