/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'community.lexicon.location.address'

type $nsid = typeof $nsid

export { $nsid }

/** A physical location in the form of a street address. */
type Main = {
  $type?: 'community.lexicon.location.address'

  /**
   * The ISO 3166 country code. Preferably the 2-letter code.
   */
  country: string

  /**
   * The postal code of the location.
   */
  postalCode?: string

  /**
   * The administrative region of the country. For example, a state in the USA.
   */
  region?: string

  /**
   * The locality of the region. For example, a city in the USA.
   */
  locality?: string

  /**
   * The street address.
   */
  street?: string

  /**
   * The name of the location.
   */
  name?: string
}

export type { Main }

/** A physical location in the form of a street address. */
const main = /*#__PURE__*/ l.typedObject<Main>(
  $nsid,
  'main',
  /*#__PURE__*/ l.object({
    country: /*#__PURE__*/ l.string({ minLength: 2, maxLength: 10 }),
    postalCode: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    region: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    locality: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    street: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    name: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
