/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RoeDefs from './defs.defs.ts'
import * as RepoStrongRef from '../../com/atproto/repo/strongRef.defs.ts'

const $nsid = 'dev.roe.ama'

type $nsid = typeof $nsid

export { $nsid }

/** An anonymous question, optionally with a published answer. While unanswered the question text is encrypted server-side (private to roe.dev). Once published, the question is rewritten in plaintext alongside the answer and per-platform URLs. */
type Main = {
  $type: 'dev.roe.ama'
  status: 'unanswered' | 'answered' | l.UnknownString

  /**
   * AES-256-GCM envelope holding the raw question text. Present iff status=unanswered.
   */
  encryptedQuestion?: string

  /**
   * Plaintext question. Present iff status=answered; the editor decrypts encryptedQuestion at publish time and writes it here so the record is self-contained going forward.
   */
  question?: string

  /**
   * Thread of response posts. Each post is the body of one Bluesky-thread item (and one Mastodon status, one LinkedIn comment chain entry, etc).
   */
  posts?: Post[]

  /**
   * Which platforms the editor enabled when publishing.
   */
  platforms?: Platforms

  /**
   * Resolved per-platform URLs after publish.
   */
  publishedLinks?: PublishedLinks
  image?: l.BlobRef

  /**
   * Pixel dimensions of `image`. Stored alongside because PDS blobs don't carry intrinsic dimensions and Bluesky's image embed needs `aspectRatio`.
   */
  imageDimensions?: RoeDefs.AspectRatio

  /**
   * ID of the background style used to render the image, either a preset name or a serialised custom emoji-and-gradient id. The set of styles is internal to roe.dev.
   */
  backgroundStyle?: string
  createdAt: l.DatetimeString
  answeredAt?: l.DatetimeString
}

export type { Main }

/** An anonymous question, optionally with a published answer. While unanswered the question text is encrypted server-side (private to roe.dev). Once published, the question is rewritten in plaintext alongside the answer and per-platform URLs. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    status: /*#__PURE__*/ l.string<{
      knownValues: ['unanswered', 'answered']
    }>(),
    encryptedQuestion: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 500000 }),
    ),
    question: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 500000, maxGraphemes: 50000 }),
    ),
    posts: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.ref<Post>((() => post) as any), {
        maxLength: 16,
      }),
    ),
    platforms: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Platforms>((() => platforms) as any),
    ),
    publishedLinks: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<PublishedLinks>((() => publishedLinks) as any),
    ),
    image: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.blob({ accept: ['image/*'], maxSize: 5000000 }),
    ),
    imageDimensions: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RoeDefs.AspectRatio>(
        (() => RoeDefs.aspectRatio) as any,
      ),
    ),
    backgroundStyle: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 128 }),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    answeredAt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** One post in the response thread. Mentions reference dev.roe.entity records by AT URI so the publisher can rewrite per-platform handles at publish time. */
type Post = {
  $type?: 'dev.roe.ama#post'

  /**
   * Body text. Plain text with `@<entity-rkey>` placeholders for entity mentions (e.g. `Thanks @abc123def456 for the help`). The placeholder syntax is internal; the publisher swaps them for the right per-platform handle.
   */
  text: string

  /**
   * Strong-refs to dev.roe.entity records. The rkey of each referenced record is the placeholder token used in `text`.
   */
  mentions?: RepoStrongRef.Main[]
}

export type { Post }

/** One post in the response thread. Mentions reference dev.roe.entity records by AT URI so the publisher can rewrite per-platform handles at publish time. */
const post = /*#__PURE__*/ l.typedObject<Post>(
  $nsid,
  'post',
  /*#__PURE__*/ l.object({
    text: /*#__PURE__*/ l.string({ maxLength: 500000, maxGraphemes: 50000 }),
    mentions: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
          (() => RepoStrongRef.main) as any,
        ),
        { maxLength: 32 },
      ),
    ),
  }),
)

export { post }

type Platforms = {
  $type?: 'dev.roe.ama#platforms'
  bluesky?: boolean
  mastodon?: boolean
  linkedin?: boolean
  youtubeShorts?: boolean
}

export type { Platforms }

const platforms = /*#__PURE__*/ l.typedObject<Platforms>(
  $nsid,
  'platforms',
  /*#__PURE__*/ l.object({
    bluesky: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.boolean(), true),
    ),
    mastodon: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.boolean(), true),
    ),
    linkedin: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.boolean(), true),
    ),
    youtubeShorts: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.boolean(), false),
    ),
  }),
)

export { platforms }

type PublishedLinks = {
  $type?: 'dev.roe.ama#publishedLinks'
  bluesky?: l.UriString
  mastodon?: l.UriString
  linkedin?: l.UriString
  youtubeShorts?: l.UriString
}

export type { PublishedLinks }

const publishedLinks = /*#__PURE__*/ l.typedObject<PublishedLinks>(
  $nsid,
  'publishedLinks',
  /*#__PURE__*/ l.object({
    bluesky: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    mastodon: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    linkedin: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    youtubeShorts: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
  }),
)

export { publishedLinks }
