/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'dev.roe.defs'

type $nsid = typeof $nsid

export { $nsid }

/** Intrinsic width:height of an image in pixels. Mirrors `app.bsky.embed.defs#aspectRatio`. */
type AspectRatio = {
  $type?: 'dev.roe.defs#aspectRatio'
  width: number
  height: number
}

export type { AspectRatio }

/** Intrinsic width:height of an image in pixels. Mirrors `app.bsky.embed.defs#aspectRatio`. */
const aspectRatio = /*#__PURE__*/ l.typedObject<AspectRatio>(
  $nsid,
  'aspectRatio',
  /*#__PURE__*/ l.object({
    width: /*#__PURE__*/ l.integer({ minimum: 1 }),
    height: /*#__PURE__*/ l.integer({ minimum: 1 }),
  }),
)

export { aspectRatio }
