/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'dev.roe.entity'

type $nsid = typeof $nsid

export { $nsid }

/** A person or organisation referenced by AMA responses via @-mentions. Holds the canonical name plus per-platform social handles so the publisher can rewrite mentions correctly for each platform. */
type Main = {
  $type: 'dev.roe.entity'
  name: string
  socialHandles?: SocialHandles
  website?: l.UriString
  createdAt: l.DatetimeString
}

export type { Main }

/** A person or organisation referenced by AMA responses via @-mentions. Holds the canonical name plus per-platform social handles so the publisher can rewrite mentions correctly for each platform. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    name: /*#__PURE__*/ l.string({ maxLength: 2560, maxGraphemes: 256 }),
    socialHandles: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<SocialHandles>((() => socialHandles) as any),
    ),
    website: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type SocialHandles = {
  $type?: 'dev.roe.entity#socialHandles'

  /**
   * Handle without leading @ (e.g. nuxt.bsky.social)
   */
  bluesky?: string

  /**
   * Company or person handle (e.g. nuxtjs)
   */
  linkedin?: string

  /**
   * Full handle including instance (e.g. nuxt@fosstodon.org)
   */
  mastodon?: string
}

export type { SocialHandles }

const socialHandles = /*#__PURE__*/ l.typedObject<SocialHandles>(
  $nsid,
  'socialHandles',
  /*#__PURE__*/ l.object({
    bluesky: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 256 }),
    ),
    linkedin: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 256 }),
    ),
    mastodon: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 256 }),
    ),
  }),
)

export { socialHandles }
