/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'dev.roe.location'

type $nsid = typeof $nsid

export { $nsid }

/** Current location (singleton; rkey is always 'self'). */
type Main = {
  $type: 'dev.roe.location'
  city: string

  /**
   * Region/state. Used to special-case Scotland and US/UK subdivisions on the public site.
   */
  region?: string
  country: string

  /**
   * ISO 3166-1 alpha-2 country code, uppercase. Used to compute a flag emoji.
   */
  countryCode: string
  meetupAvailable?: boolean
  createdAt: l.DatetimeString
}

export type { Main }

/** Current location (singleton; rkey is always 'self'). */
const main = /*#__PURE__*/ l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  /*#__PURE__*/ l.object({
    city: /*#__PURE__*/ l.string({ maxLength: 2560, maxGraphemes: 256 }),
    region: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 2560, maxGraphemes: 256 }),
    ),
    country: /*#__PURE__*/ l.string({ maxLength: 2560, maxGraphemes: 256 }),
    countryCode: /*#__PURE__*/ l.string({ minLength: 2, maxLength: 2 }),
    meetupAvailable: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.boolean(), true),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
