/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../com/atproto/repo/strongRef.defs.ts'
import * as AppDefs from '../../community/lexicon/app/defs.defs.ts'

const $nsid = 'dev.roe.project'

type $nsid = typeof $nsid

export { $nsid }

/** A project on the /projects page, belonging to a dev.roe.projectCategory. */
type Main = {
  $type: 'dev.roe.project'

  /**
   * Strong-ref to the parent dev.roe.projectCategory record.
   */
  category: RepoStrongRef.Main
  name: string
  description?: string

  /**
   * Relevant destinations for the project. The site links the card at the first `linkRoleWebsite`, falling back to the first link of any role.
   */
  links?: AppDefs.Link[]

  /**
   * Visual assets for the project. The site renders the first `purposeScreenshot`, falling back to the first image of any purpose.
   */
  images?: AppDefs.Image[]

  /**
   * Release or maintenance status. `unmaintained` and `discontinued` render the card as archived.
   */
  status?: AppDefs.Status

  /**
   * UnoCSS icon class, e.g. `i-ri:rocket-line`. Used when there is no image.
   */
  icon?: string

  /**
   * Lower values render first within the category. Defaults to 100 in the editor.
   */
  order?: number
  createdAt: l.DatetimeString
}

export type { Main }

/** A project on the /projects page, belonging to a dev.roe.projectCategory. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    category: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    name: /*#__PURE__*/ l.string({ maxLength: 2560, maxGraphemes: 256 }),
    description: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 25000, maxGraphemes: 2500 }),
    ),
    links: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<AppDefs.Link>((() => AppDefs.link) as any),
        { maxLength: 12 },
      ),
    ),
    images: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<AppDefs.Image>((() => AppDefs.image) as any),
        { maxLength: 8 },
      ),
    ),
    status: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<AppDefs.Status>((() => AppDefs.status) as any),
    ),
    icon: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 640, maxGraphemes: 64 }),
    ),
    order: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.integer(), 100),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
