/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../com/atproto/repo/strongRef.defs.ts'
import * as RoeDefs from './defs.defs.ts'

const $nsid = 'dev.roe.talk'

type $nsid = typeof $nsid

export { $nsid }

/** A talk, podcast appearance, workshop, stream, or similar event. */
type Main = {
  $type: 'dev.roe.talk'

  /**
   * Optional for upcoming events with no announced title. Required for past talks unless the talk is part of a group.
   */
  title?: string
  description?: string

  /**
   * Start date of the talk/event. Date-only values are stored as midnight UTC.
   */
  date: l.DatetimeString

  /**
   * End date for multi-day events. Optional.
   */
  endDate?: l.DatetimeString

  /**
   * Conference name, meetup, podcast title, etc.
   */
  source: string

  /**
   * Free-form: city, country, or 'Online'.
   */
  location?: string
  type:
    | 'conference'
    | 'meetup'
    | 'podcast'
    | 'workshop'
    | 'stream'
    | 'talk'
    | l.UnknownString
  tags?: string[]

  /**
   * Event page, podcast episode URL, etc.
   */
  link?: l.UriString
  video?: l.UriString

  /**
   * Identifier for slides; historically a GitHub release tag from danielroe/slides.
   */
  slides?: string
  demo?: l.UriString
  repo?: l.UriString

  /**
   * Strong-ref to a dev.roe.talkGroup record.
   */
  group?: RepoStrongRef.Main
  image?: l.BlobRef

  /**
   * Intrinsic pixel dimensions of `image`.
   */
  aspectRatio?: RoeDefs.AspectRatio
  createdAt: l.DatetimeString
}

export type { Main }

/** A talk, podcast appearance, workshop, stream, or similar event. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    title: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 5120, maxGraphemes: 512 }),
    ),
    description: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 50000, maxGraphemes: 5000 }),
    ),
    date: /*#__PURE__*/ l.string({ format: 'datetime' }),
    endDate: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
    source: /*#__PURE__*/ l.string({ maxLength: 5120, maxGraphemes: 512 }),
    location: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 5120, maxGraphemes: 512 }),
    ),
    type: /*#__PURE__*/ l.string<{
      knownValues: [
        'conference',
        'meetup',
        'podcast',
        'workshop',
        'stream',
        'talk',
      ]
    }>(),
    tags: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.string({ maxLength: 640, maxGraphemes: 64 }),
        { maxLength: 32 },
      ),
    ),
    link: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'uri' })),
    video: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'uri' })),
    slides: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 512 }),
    ),
    demo: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'uri' })),
    repo: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'uri' })),
    group: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
        (() => RepoStrongRef.main) as any,
      ),
    ),
    image: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.blob({ accept: ['image/*'], maxSize: 5000000 }),
    ),
    aspectRatio: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RoeDefs.AspectRatio>(
        (() => RoeDefs.aspectRatio) as any,
      ),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
