/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../com/atproto/repo/strongRef.defs.ts'
import * as RoeDefs from './defs.defs.ts'

const $nsid = 'dev.roe.usesItem'

type $nsid = typeof $nsid

export { $nsid }

/** A single item on the /uses page, belonging to a dev.roe.usesCategory. */
type Main = {
  $type: 'dev.roe.usesItem'

  /**
   * Strong-ref to the parent dev.roe.usesCategory record.
   */
  category: RepoStrongRef.Main
  name: string
  description?: string

  /**
   * Lower values render first within the category. Defaults to 100 in the editor.
   */
  order?: number
  image?: l.BlobRef

  /**
   * Intrinsic pixel dimensions of `image`.
   */
  aspectRatio?: RoeDefs.AspectRatio
  links?: Link[]
  createdAt: l.DatetimeString
}

export type { Main }

/** A single item on the /uses page, belonging to a dev.roe.usesCategory. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    category: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    name: /*#__PURE__*/ l.string({ maxLength: 2560, maxGraphemes: 256 }),
    description: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 25000, maxGraphemes: 2500 }),
    ),
    order: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.integer(), 100),
    ),
    image: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.blob({ accept: ['image/*'], maxSize: 5000000 }),
    ),
    aspectRatio: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RoeDefs.AspectRatio>(
        (() => RoeDefs.aspectRatio) as any,
      ),
    ),
    links: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.ref<Link>((() => link) as any), {
        maxLength: 32,
      }),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type Link = {
  $type?: 'dev.roe.usesItem#link'
  url: l.UriString
  label?: string
}

export type { Link }

const link = /*#__PURE__*/ l.typedObject<Link>(
  $nsid,
  'link',
  /*#__PURE__*/ l.object({
    url: /*#__PURE__*/ l.string({ format: 'uri' }),
    label: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 640, maxGraphemes: 64 }),
    ),
  }),
)

export { link }
