// @ts-expect-error virtual file generated by bsky-comments module
import { pendingPosts } from 'bsky-runtime-discovery-server.mjs'
import { BLUESKY_API, postLinksToUrl, type BlueskyFeedResponse } from '#shared/utils/bluesky'

const posts = pendingPosts as Record<string, { url: string, date: string }>

export default defineCachedEventHandler(async event => {
  const path = getQuery(event).path
  const post = typeof path === 'string' ? posts[path] : undefined
  if (!post) {
    return { uri: null }
  }

  const bskyHandle = useRuntimeConfig(event).social.networks.bluesky.identifier
  const searchCutoff = new Date(new Date(post.date).getTime() - 24 * 60 * 60 * 1000)

  let cursor: string | undefined

  // Iterate through feed until we find a match or reach the day before the post
  do {
    const response = await $fetch<BlueskyFeedResponse>('/xrpc/app.bsky.feed.getAuthorFeed', {
      baseURL: BLUESKY_API,
      query: {
        actor: bskyHandle,
        limit: 100,
        cursor,
      },
    })

    for (const item of response.feed) {
      if (item.reason) continue

      // Check if we've gone past the search cutoff
      if (new Date(item.post.record.createdAt) < searchCutoff) {
        return { uri: null }
      }

      if (postLinksToUrl(item.post, post.url)) {
        return { uri: item.post.uri }
      }
    }

    cursor = response.cursor
  } while (cursor)

  return { uri: null }
}, {
  maxAge: 60 * 60,
  swr: true,
  getKey: event => String(getQuery(event).path || ''),
})
