/** @vitest-environment node */

import { fileURLToPath } from 'node:url'
import fsp from 'node:fs/promises'

import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import execa from 'execa'
import { globby } from 'globby'
import { join } from 'pathe'

describe('project sizes', () => {
  const rootDir = fileURLToPath(new URL('../..', import.meta.url))
  const publicDir = join(rootDir, '.output/public')
  const serverDir = join(rootDir, '.output/server')

  const stats = {
    client: { totalBytes: 0, files: [] as string[] },
    server: { totalBytes: 0, files: [] as string[] },
  }

  beforeAll(async () => {
    await execa('pnpm', ['nuxi', 'build'], {
      cwd: rootDir,
      env: { DISABLE_PRERENDER: 'true' },
    })
  }, 120 * 1000)

  afterAll(async () => {
    await fsp.writeFile(
      join(rootDir, '.output/test-stats.json'),
      JSON.stringify(stats, null, 2)
    )
  })

  it('default client bundle size', async () => {
    stats.client = await analyzeSizes('**/*.js', publicDir)
    expect
      .soft(roundToKilobytes(stats.client.totalBytes))
      .toMatchInlineSnapshot('"193k"')
    expect.soft(stats.client.files.map(f => f.replace(/\..*\.js/, '.js')))
      .toMatchInlineSnapshot(`
        [
          "_nuxt/CalSchedule.js",
          "_nuxt/ContentRendererMarkdown.js",
          "_nuxt/NuxtTime.js",
          "_nuxt/ProseA.js",
          "_nuxt/ProseBlockquote.js",
          "_nuxt/ProseCode.js",
          "_nuxt/ProseCode.js",
          "_nuxt/ProseCodeInline.js",
          "_nuxt/ProseEm.js",
          "_nuxt/ProseH1.js",
          "_nuxt/ProseH2.js",
          "_nuxt/ProseH3.js",
          "_nuxt/ProseH4.js",
          "_nuxt/ProseH5.js",
          "_nuxt/ProseH6.js",
          "_nuxt/ProseHr.js",
          "_nuxt/ProseImg.js",
          "_nuxt/ProseLi.js",
          "_nuxt/ProseOl.js",
          "_nuxt/ProseP.js",
          "_nuxt/ProsePre.js",
          "_nuxt/ProseStrong.js",
          "_nuxt/ProseTable.js",
          "_nuxt/ProseTbody.js",
          "_nuxt/ProseTd.js",
          "_nuxt/ProseTh.js",
          "_nuxt/ProseThead.js",
          "_nuxt/ProseTr.js",
          "_nuxt/ProseUl.js",
          "_nuxt/SocialPost.js",
          "_nuxt/_article_.js",
          "_nuxt/entry.js",
          "_nuxt/feed.js",
          "_nuxt/index.js",
          "_nuxt/index.js",
          "_nuxt/talks.js",
          "_nuxt/uses.js",
          "_nuxt/voted.js",
          "_nuxt/work.js",
        ]
      `)
  })

  it('default server bundle size', async () => {
    stats.server = await analyzeSizes(['**/*.mjs', '!node_modules'], serverDir)
    expect
      .soft(roundToKilobytes(stats.server.totalBytes))
      .toMatchInlineSnapshot('"629k"')

    const modules = await analyzeSizes('node_modules/**/*', serverDir)
    expect
      .soft(roundToKilobytes(modules.totalBytes))
      .toMatchInlineSnapshot('"28867k"')

    const packages = modules.files
      .filter(m => m.endsWith('package.json'))
      .map(m => m.replace('/package.json', '').replace('node_modules/', ''))
      .sort()
    expect.soft(packages).toMatchInlineSnapshot(`
      [
        "@atproto/api",
        "@fastify/accept-negotiator",
        "@sindresorhus/is",
        "@ungap/structured-clone",
        "abort-controller",
        "asynckit",
        "bail",
        "ccount",
        "char-regex",
        "character-entities",
        "character-entities-html4",
        "character-entities-legacy",
        "character-reference-invalid",
        "color",
        "color-convert",
        "color-name",
        "color-string",
        "combined-stream",
        "comma-separated-tokens",
        "cookie-es",
        "decode-named-character-reference",
        "defu",
        "delayed-stream",
        "destr",
        "detab",
        "detect-libc",
        "devlop",
        "emojilib",
        "emoticon",
        "escape-string-regexp",
        "etag",
        "event-target-shim",
        "extend",
        "feed",
        "flat",
        "form-data",
        "github-slugger",
        "h3",
        "hast-util-from-parse5",
        "hast-util-is-element",
        "hast-util-parse-selector",
        "hast-util-raw",
        "hast-util-raw/node_modules/unist-util-visit",
        "hast-util-raw/node_modules/unist-util-visit/node_modules/unist-util-visit-parents",
        "hast-util-raw/node_modules/unist-util-visit/node_modules/unist-util-visit-parents/node_modules/unist-util-is",
        "hast-util-to-parse5",
        "hast-util-to-string",
        "hastscript",
        "html-void-elements",
        "image-meta",
        "ipx",
        "iron-webcrypto",
        "is-absolute-url",
        "is-alphabetical",
        "is-alphanumerical",
        "is-arrayish",
        "is-decimal",
        "is-hexadecimal",
        "is-plain-obj",
        "js-yaml",
        "json5",
        "longest-streak",
        "markdown-table",
        "mdast-util-definitions",
        "mdast-util-definitions/node_modules/unist-util-visit",
        "mdast-util-definitions/node_modules/unist-util-visit/node_modules/unist-util-visit-parents",
        "mdast-util-definitions/node_modules/unist-util-visit/node_modules/unist-util-visit-parents/node_modules/unist-util-is",
        "mdast-util-find-and-replace",
        "mdast-util-find-and-replace/node_modules/unist-util-is",
        "mdast-util-find-and-replace/node_modules/unist-util-visit-parents",
        "mdast-util-find-and-replace/node_modules/unist-util-visit-parents/node_modules/unist-util-is",
        "mdast-util-from-markdown",
        "mdast-util-from-markdown/node_modules/mdast-util-to-string",
        "mdast-util-from-markdown/node_modules/micromark",
        "mdast-util-from-markdown/node_modules/micromark-util-decode-numeric-character-reference",
        "mdast-util-from-markdown/node_modules/micromark-util-decode-string",
        "mdast-util-from-markdown/node_modules/micromark-util-decode-string/node_modules/micromark-util-decode-numeric-character-reference",
        "mdast-util-from-markdown/node_modules/micromark-util-normalize-identifier",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-destination",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-destination/node_modules/micromark-util-character",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-label",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-label/node_modules/micromark-util-character",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-space",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-title",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-title/node_modules/micromark-factory-space",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-title/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-title/node_modules/micromark-util-character",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-whitespace",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-whitespace/node_modules/micromark-factory-space",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-whitespace/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-whitespace/node_modules/micromark-util-character",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-util-character",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-util-chunked",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-util-classify-character",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-util-classify-character/node_modules/micromark-util-character",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-util-html-tag-name",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-util-normalize-identifier",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-util-resolve-all",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-util-subtokenize",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-core-commonmark/node_modules/micromark-util-subtokenize/node_modules/micromark-util-chunked",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-factory-space",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-util-character",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-util-chunked",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-util-combine-extensions",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-util-combine-extensions/node_modules/micromark-util-chunked",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-util-resolve-all",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-util-subtokenize",
        "mdast-util-from-markdown/node_modules/micromark/node_modules/micromark-util-subtokenize/node_modules/micromark-util-chunked",
        "mdast-util-from-markdown/node_modules/unist-util-stringify-position",
        "mdast-util-gfm",
        "mdast-util-gfm-autolink-literal",
        "mdast-util-gfm-autolink-literal/node_modules/mdast-util-find-and-replace",
        "mdast-util-gfm-autolink-literal/node_modules/mdast-util-find-and-replace/node_modules/unist-util-is",
        "mdast-util-gfm-autolink-literal/node_modules/mdast-util-find-and-replace/node_modules/unist-util-visit-parents",
        "mdast-util-gfm-autolink-literal/node_modules/mdast-util-find-and-replace/node_modules/unist-util-visit-parents/node_modules/unist-util-is",
        "mdast-util-gfm-autolink-literal/node_modules/micromark-util-character",
        "mdast-util-gfm-footnote",
        "mdast-util-gfm-footnote/node_modules/mdast-util-to-markdown",
        "mdast-util-gfm-footnote/node_modules/mdast-util-to-markdown/node_modules/micromark-util-decode-string",
        "mdast-util-gfm-footnote/node_modules/mdast-util-to-markdown/node_modules/micromark-util-decode-string/node_modules/micromark-util-decode-numeric-character-reference",
        "mdast-util-gfm-footnote/node_modules/micromark-util-normalize-identifier",
        "mdast-util-gfm-strikethrough",
        "mdast-util-gfm-strikethrough/node_modules/mdast-util-to-markdown",
        "mdast-util-gfm-strikethrough/node_modules/mdast-util-to-markdown/node_modules/micromark-util-decode-string",
        "mdast-util-gfm-strikethrough/node_modules/mdast-util-to-markdown/node_modules/micromark-util-decode-string/node_modules/micromark-util-decode-numeric-character-reference",
        "mdast-util-gfm-table",
        "mdast-util-gfm-table/node_modules/mdast-util-to-markdown",
        "mdast-util-gfm-table/node_modules/mdast-util-to-markdown/node_modules/micromark-util-decode-string",
        "mdast-util-gfm-table/node_modules/mdast-util-to-markdown/node_modules/micromark-util-decode-string/node_modules/micromark-util-decode-numeric-character-reference",
        "mdast-util-gfm-task-list-item",
        "mdast-util-gfm-task-list-item/node_modules/mdast-util-to-markdown",
        "mdast-util-gfm-task-list-item/node_modules/mdast-util-to-markdown/node_modules/micromark-util-decode-string",
        "mdast-util-gfm-task-list-item/node_modules/mdast-util-to-markdown/node_modules/micromark-util-decode-string/node_modules/micromark-util-decode-numeric-character-reference",
        "mdast-util-phrasing",
        "mdast-util-phrasing/node_modules/unist-util-is",
        "mdast-util-to-hast",
        "mdast-util-to-hast/node_modules/micromark-util-sanitize-uri",
        "mdast-util-to-hast/node_modules/micromark-util-sanitize-uri/node_modules/micromark-util-character",
        "mdast-util-to-hast/node_modules/micromark-util-sanitize-uri/node_modules/micromark-util-encode",
        "mdast-util-to-hast/node_modules/unist-util-visit",
        "mdast-util-to-hast/node_modules/unist-util-visit/node_modules/unist-util-visit-parents",
        "mdast-util-to-hast/node_modules/unist-util-visit/node_modules/unist-util-visit-parents/node_modules/unist-util-is",
        "mdast-util-to-markdown",
        "mdast-util-to-markdown/node_modules/mdast-util-to-string",
        "mdast-util-to-markdown/node_modules/micromark-util-decode-string",
        "mdast-util-to-markdown/node_modules/micromark-util-decode-string/node_modules/micromark-util-decode-numeric-character-reference",
        "mdast-util-to-markdown/node_modules/unist-util-visit",
        "mdast-util-to-markdown/node_modules/unist-util-visit/node_modules/unist-util-visit-parents",
        "mdast-util-to-markdown/node_modules/unist-util-visit/node_modules/unist-util-visit-parents/node_modules/unist-util-is",
        "mdast-util-to-string",
        "micromark",
        "micromark-core-commonmark",
        "micromark-core-commonmark/node_modules/micromark-factory-destination",
        "micromark-core-commonmark/node_modules/micromark-factory-destination/node_modules/micromark-util-character",
        "micromark-core-commonmark/node_modules/micromark-factory-label",
        "micromark-core-commonmark/node_modules/micromark-factory-label/node_modules/micromark-util-character",
        "micromark-core-commonmark/node_modules/micromark-factory-space",
        "micromark-core-commonmark/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "micromark-core-commonmark/node_modules/micromark-factory-title",
        "micromark-core-commonmark/node_modules/micromark-factory-title/node_modules/micromark-factory-space",
        "micromark-core-commonmark/node_modules/micromark-factory-title/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "micromark-core-commonmark/node_modules/micromark-factory-title/node_modules/micromark-util-character",
        "micromark-core-commonmark/node_modules/micromark-factory-whitespace",
        "micromark-core-commonmark/node_modules/micromark-factory-whitespace/node_modules/micromark-factory-space",
        "micromark-core-commonmark/node_modules/micromark-factory-whitespace/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "micromark-core-commonmark/node_modules/micromark-factory-whitespace/node_modules/micromark-util-character",
        "micromark-core-commonmark/node_modules/micromark-util-character",
        "micromark-core-commonmark/node_modules/micromark-util-chunked",
        "micromark-core-commonmark/node_modules/micromark-util-classify-character",
        "micromark-core-commonmark/node_modules/micromark-util-classify-character/node_modules/micromark-util-character",
        "micromark-core-commonmark/node_modules/micromark-util-html-tag-name",
        "micromark-core-commonmark/node_modules/micromark-util-normalize-identifier",
        "micromark-core-commonmark/node_modules/micromark-util-resolve-all",
        "micromark-core-commonmark/node_modules/micromark-util-subtokenize",
        "micromark-core-commonmark/node_modules/micromark-util-subtokenize/node_modules/micromark-util-chunked",
        "micromark-extension-gfm",
        "micromark-extension-gfm-autolink-literal",
        "micromark-extension-gfm-autolink-literal/node_modules/micromark-util-character",
        "micromark-extension-gfm-autolink-literal/node_modules/micromark-util-sanitize-uri",
        "micromark-extension-gfm-autolink-literal/node_modules/micromark-util-sanitize-uri/node_modules/micromark-util-character",
        "micromark-extension-gfm-autolink-literal/node_modules/micromark-util-sanitize-uri/node_modules/micromark-util-encode",
        "micromark-extension-gfm-footnote",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-factory-destination",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-factory-destination/node_modules/micromark-util-character",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-factory-label",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-factory-label/node_modules/micromark-util-character",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-factory-space",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-factory-title",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-factory-title/node_modules/micromark-factory-space",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-factory-title/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-factory-title/node_modules/micromark-util-character",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-factory-whitespace",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-factory-whitespace/node_modules/micromark-factory-space",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-factory-whitespace/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-factory-whitespace/node_modules/micromark-util-character",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-util-character",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-util-chunked",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-util-classify-character",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-util-classify-character/node_modules/micromark-util-character",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-util-html-tag-name",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-util-normalize-identifier",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-util-resolve-all",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-util-subtokenize",
        "micromark-extension-gfm-footnote/node_modules/micromark-core-commonmark/node_modules/micromark-util-subtokenize/node_modules/micromark-util-chunked",
        "micromark-extension-gfm-footnote/node_modules/micromark-factory-space",
        "micromark-extension-gfm-footnote/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "micromark-extension-gfm-footnote/node_modules/micromark-util-character",
        "micromark-extension-gfm-footnote/node_modules/micromark-util-normalize-identifier",
        "micromark-extension-gfm-footnote/node_modules/micromark-util-sanitize-uri",
        "micromark-extension-gfm-footnote/node_modules/micromark-util-sanitize-uri/node_modules/micromark-util-character",
        "micromark-extension-gfm-footnote/node_modules/micromark-util-sanitize-uri/node_modules/micromark-util-encode",
        "micromark-extension-gfm-strikethrough",
        "micromark-extension-gfm-strikethrough/node_modules/micromark-util-chunked",
        "micromark-extension-gfm-strikethrough/node_modules/micromark-util-classify-character",
        "micromark-extension-gfm-strikethrough/node_modules/micromark-util-classify-character/node_modules/micromark-util-character",
        "micromark-extension-gfm-strikethrough/node_modules/micromark-util-resolve-all",
        "micromark-extension-gfm-table",
        "micromark-extension-gfm-table/node_modules/micromark-factory-space",
        "micromark-extension-gfm-table/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "micromark-extension-gfm-table/node_modules/micromark-util-character",
        "micromark-extension-gfm-tagfilter",
        "micromark-extension-gfm-task-list-item",
        "micromark-extension-gfm-task-list-item/node_modules/micromark-factory-space",
        "micromark-extension-gfm-task-list-item/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "micromark-extension-gfm-task-list-item/node_modules/micromark-util-character",
        "micromark-extension-gfm/node_modules/micromark-util-combine-extensions",
        "micromark-extension-gfm/node_modules/micromark-util-combine-extensions/node_modules/micromark-util-chunked",
        "micromark-factory-destination",
        "micromark-factory-destination/node_modules/micromark-util-character",
        "micromark-factory-label",
        "micromark-factory-label/node_modules/micromark-util-character",
        "micromark-factory-space",
        "micromark-factory-space/node_modules/micromark-util-character",
        "micromark-factory-title",
        "micromark-factory-title/node_modules/micromark-factory-space",
        "micromark-factory-title/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "micromark-factory-title/node_modules/micromark-util-character",
        "micromark-factory-whitespace",
        "micromark-factory-whitespace/node_modules/micromark-factory-space",
        "micromark-factory-whitespace/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "micromark-factory-whitespace/node_modules/micromark-util-character",
        "micromark-util-character",
        "micromark-util-chunked",
        "micromark-util-classify-character",
        "micromark-util-classify-character/node_modules/micromark-util-character",
        "micromark-util-combine-extensions",
        "micromark-util-combine-extensions/node_modules/micromark-util-chunked",
        "micromark-util-decode-numeric-character-reference",
        "micromark-util-decode-string",
        "micromark-util-decode-string/node_modules/micromark-util-decode-numeric-character-reference",
        "micromark-util-encode",
        "micromark-util-html-tag-name",
        "micromark-util-normalize-identifier",
        "micromark-util-resolve-all",
        "micromark-util-sanitize-uri",
        "micromark-util-sanitize-uri/node_modules/micromark-util-character",
        "micromark-util-sanitize-uri/node_modules/micromark-util-encode",
        "micromark-util-subtokenize",
        "micromark-util-subtokenize/node_modules/micromark-util-chunked",
        "micromark/node_modules/micromark-core-commonmark",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-destination",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-destination/node_modules/micromark-util-character",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-label",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-label/node_modules/micromark-util-character",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-space",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-title",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-title/node_modules/micromark-factory-space",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-title/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-title/node_modules/micromark-util-character",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-whitespace",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-whitespace/node_modules/micromark-factory-space",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-whitespace/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-factory-whitespace/node_modules/micromark-util-character",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-util-character",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-util-chunked",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-util-classify-character",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-util-classify-character/node_modules/micromark-util-character",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-util-html-tag-name",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-util-normalize-identifier",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-util-resolve-all",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-util-subtokenize",
        "micromark/node_modules/micromark-core-commonmark/node_modules/micromark-util-subtokenize/node_modules/micromark-util-chunked",
        "micromark/node_modules/micromark-factory-space",
        "micromark/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "micromark/node_modules/micromark-util-character",
        "micromark/node_modules/micromark-util-chunked",
        "micromark/node_modules/micromark-util-combine-extensions",
        "micromark/node_modules/micromark-util-combine-extensions/node_modules/micromark-util-chunked",
        "micromark/node_modules/micromark-util-decode-numeric-character-reference",
        "micromark/node_modules/micromark-util-encode",
        "micromark/node_modules/micromark-util-normalize-identifier",
        "micromark/node_modules/micromark-util-resolve-all",
        "micromark/node_modules/micromark-util-sanitize-uri",
        "micromark/node_modules/micromark-util-sanitize-uri/node_modules/micromark-util-character",
        "micromark/node_modules/micromark-util-sanitize-uri/node_modules/micromark-util-encode",
        "micromark/node_modules/micromark-util-subtokenize",
        "micromark/node_modules/micromark-util-subtokenize/node_modules/micromark-util-chunked",
        "mime-db",
        "mime-types",
        "node-emoji",
        "node-fetch-native",
        "ofetch",
        "parse-entities",
        "parse5",
        "pathe",
        "property-information",
        "radix3",
        "rehype-external-links",
        "rehype-external-links/node_modules/unist-util-visit",
        "rehype-external-links/node_modules/unist-util-visit/node_modules/unist-util-visit-parents",
        "rehype-external-links/node_modules/unist-util-visit/node_modules/unist-util-visit-parents/node_modules/unist-util-is",
        "rehype-raw",
        "rehype-sort-attribute-values",
        "rehype-sort-attribute-values/node_modules/unist-util-visit",
        "rehype-sort-attribute-values/node_modules/unist-util-visit/node_modules/unist-util-visit-parents",
        "rehype-sort-attribute-values/node_modules/unist-util-visit/node_modules/unist-util-visit-parents/node_modules/unist-util-is",
        "rehype-sort-attributes",
        "rehype-sort-attributes/node_modules/unist-util-visit",
        "rehype-sort-attributes/node_modules/unist-util-visit/node_modules/unist-util-visit-parents",
        "rehype-sort-attributes/node_modules/unist-util-visit/node_modules/unist-util-visit-parents/node_modules/unist-util-is",
        "remark-emoji",
        "remark-emoji/node_modules/mdast-util-find-and-replace",
        "remark-emoji/node_modules/mdast-util-find-and-replace/node_modules/unist-util-is",
        "remark-emoji/node_modules/mdast-util-find-and-replace/node_modules/unist-util-visit-parents",
        "remark-emoji/node_modules/mdast-util-find-and-replace/node_modules/unist-util-visit-parents/node_modules/unist-util-is",
        "remark-gfm",
        "remark-mdc",
        "remark-mdc/node_modules/mdast-util-to-markdown",
        "remark-mdc/node_modules/mdast-util-to-markdown/node_modules/mdast-util-to-string",
        "remark-mdc/node_modules/mdast-util-to-markdown/node_modules/micromark-util-decode-string",
        "remark-mdc/node_modules/mdast-util-to-markdown/node_modules/micromark-util-decode-string/node_modules/micromark-util-decode-numeric-character-reference",
        "remark-mdc/node_modules/mdast-util-to-markdown/node_modules/unist-util-visit",
        "remark-mdc/node_modules/mdast-util-to-markdown/node_modules/unist-util-visit/node_modules/unist-util-visit-parents",
        "remark-mdc/node_modules/mdast-util-to-markdown/node_modules/unist-util-visit/node_modules/unist-util-visit-parents/node_modules/unist-util-is",
        "remark-mdc/node_modules/micromark-core-commonmark",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-factory-destination",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-factory-destination/node_modules/micromark-util-character",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-factory-label",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-factory-label/node_modules/micromark-util-character",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-factory-space",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-factory-title",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-factory-title/node_modules/micromark-factory-space",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-factory-title/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-factory-title/node_modules/micromark-util-character",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-factory-whitespace",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-factory-whitespace/node_modules/micromark-factory-space",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-factory-whitespace/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-factory-whitespace/node_modules/micromark-util-character",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-util-character",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-util-chunked",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-util-classify-character",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-util-classify-character/node_modules/micromark-util-character",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-util-html-tag-name",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-util-normalize-identifier",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-util-resolve-all",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-util-subtokenize",
        "remark-mdc/node_modules/micromark-core-commonmark/node_modules/micromark-util-subtokenize/node_modules/micromark-util-chunked",
        "remark-mdc/node_modules/micromark-factory-space",
        "remark-mdc/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "remark-mdc/node_modules/micromark-factory-whitespace",
        "remark-mdc/node_modules/micromark-factory-whitespace/node_modules/micromark-factory-space",
        "remark-mdc/node_modules/micromark-factory-whitespace/node_modules/micromark-factory-space/node_modules/micromark-util-character",
        "remark-mdc/node_modules/micromark-factory-whitespace/node_modules/micromark-util-character",
        "remark-mdc/node_modules/micromark-util-character",
        "remark-mdc/node_modules/unist-util-visit",
        "remark-mdc/node_modules/unist-util-visit/node_modules/unist-util-visit-parents",
        "remark-mdc/node_modules/unist-util-visit/node_modules/unist-util-visit-parents/node_modules/unist-util-is",
        "remark-parse",
        "remark-rehype",
        "sax",
        "scule",
        "semver",
        "sharp",
        "shikiji",
        "simple-swizzle",
        "skin-tone",
        "slugify",
        "space-separated-tokens",
        "stringify-entities",
        "trim-lines",
        "trough",
        "ufo",
        "uncrypto",
        "unenv",
        "unicode-emoji-modifier-base",
        "unified",
        "unist-util-generated",
        "unist-util-is",
        "unist-util-position",
        "unist-util-stringify-position",
        "unist-util-visit",
        "unist-util-visit-parents",
        "unist-util-visit-parents/node_modules/unist-util-is",
        "unist-util-visit/node_modules/unist-util-visit-parents",
        "unist-util-visit/node_modules/unist-util-visit-parents/node_modules/unist-util-is",
        "vfile",
        "vfile-location",
        "vfile-message",
        "vfile-message/node_modules/unist-util-stringify-position",
        "web-namespaces",
        "xml-js",
        "zwitch",
      ]
    `)
  })
})

async function analyzeSizes(pattern: string | string[], rootDir: string) {
  const files: string[] = await globby(pattern, { cwd: rootDir })
  let totalBytes = 0
  for (const file of files) {
    const path = join(rootDir, file)
    const isSymlink = (
      await fsp.lstat(path).catch(() => null)
    )?.isSymbolicLink()

    if (!isSymlink) {
      const bytes = Buffer.byteLength(await fsp.readFile(path))
      totalBytes += bytes
    }
  }
  return { files, totalBytes }
}

function roundToKilobytes(bytes: number) {
  return (bytes / 1024).toFixed(bytes > 100 * 1024 ? 0 : 1) + 'k'
}
